fix: Remove descriptions from minified SDL output (#1)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,8 @@
-on: [push, pull_request]
+on:
+  pull_request:
+  push:
+    branches:
+      - main # Replace with your default branch if different
 name: Test
 jobs:
   lint:
@@ -10,7 +14,7 @@ jobs:
       - name: Install Go
         uses: actions/setup-go@v5
         with:
-          go-version: 1.x
+          go-version: '1.24.2'
 
       - name: fmt
         run: test -z $(gofmt -l .)
@@ -18,15 +22,25 @@ jobs:
       - name: vet
         run: go vet ./...
 
+      - name: Install staticcheck
+        run: go install honnef.co/go/tools/cmd/staticcheck@latest
+
+      - name: Check Go version
+        run: go version
+        
+      - name: Check staticcheck path
+        run: command -v staticcheck || echo "staticcheck not found in PATH"
+        
+      - name: Check GOPATH bin
+        run: echo "$(go env GOPATH)/bin"
+
       - name: staticcheck
-        uses: dominikh/staticcheck-action@v1.3.0
-        with:
-          install-go: false
+        run: $(go env GOPATH)/bin/staticcheck ./...
 
   test:
     strategy:
       matrix:
-        go-version: [1.x]
+        go-version: ['1.24.2']
         os: [ubuntu-latest, macos-latest, windows-latest]
     runs-on: ${{ matrix.os }}
     steps:
